#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Георгий Устинов
License: zlib/libpng
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from pathlib import Path
from typing import Callable
from time import monotonic

from subtask_stress_test import a_lot_of_frames
from subtask_intro import render_intro


TITLE = "gen_images.py"

DESCRIPTION = """
  Test data generator for Catframes.

  This script is a part of Catframes repository.
  https://github.com/georgy7/catframes

  Dependencies:
  - pycairo

  The frames generated by this script can, for example, be combined with an audio track
  using a command such as `ffmpeg -r 60 -i %d.png -i audio.mp3 -shortest output.mp4`.
"""

SubTask = Callable[[Path], None]


class ConsoleInterface:
    __slots__ = ('destination',)

    def __init__(self) -> None:
        self.destination: Path = Path()

        parser = ArgumentParser(prog=TITLE, description=DESCRIPTION,
            formatter_class=RawDescriptionHelpFormatter)

        parser.add_argument('destination', metavar='DESTINATION', nargs=1,
            help="The output folder path. It doesn't have to exist.")

        args = parser.parse_args()

        p: Path = Path(args.destination[0]).expanduser().absolute()

        if p.is_dir() or (p.parent.is_dir() and not p.exists()):
            self.destination = p
        elif p.is_file():
            parser.error('The destination must be a folder, not a file.')
        elif not p.parent.is_dir():
            parser.error('A parent folder of the destination folder must exist.')
        else:
            parser.error('Something wrong with the destination path.')


def run(folder: Path, subtask: SubTask):
    if folder.is_dir():
        print(f'The folder "{folder.name}" already exists.')
    else:
        if folder.exists():
            print(f'The path "{folder.name}" is not a folder. Deleting it...')
            folder.unlink(missing_ok=True)
        folder.mkdir()
        subtask(folder)


def main() -> None:
    cli = ConsoleInterface()
    cli.destination.mkdir(exist_ok=True)
    run(cli.destination / 'a_lot_of_frames', a_lot_of_frames)
    run(cli.destination / 'intro', render_intro)
    print("Finished")


if __name__ == "__main__":
    start_time = monotonic()
    main()
    print(monotonic() - start_time)

